### PR TITLE
Fixes issue 99

### LINKED ISSUE #99: Cannot run main.py with any file in /src
Running `python3 main.py src/orbit1.csv` results in `ValueError: cannot reshape array of size 33 into shape (3,)`

### PR DESCRIPTION
**Pull request by aryadas98**
Fixes #99.

Sets multi_rev to 0 in lamberts_kalman.py. This makes the output array have the required shape.

Limits the cosines in state_kep.py to be between -1 and 1. Sometimes, due to floating point errors, it can go out of limit.

Adds a new command line option to choose between metres and kilometres.

### CODE REVIEW

**Comment by Alexandros23Kazantzidis** [comment]
Yeah the m and km change is useful we need that. The cosine change is also something I like but for the Lamberts I want some time to check it and test it to see if I get the correct results. Thank you for the help keep on digging for issues and bugs

**Comment by aryadas98** [comment]
Right now, the default unit is kilometres. Should it remain so, or should I switch the default unit to metres?

**Comment by Alexandros23Kazantzidis** [comment]
I remember Andreas told us for the default unit to be in kilometers so yes

**Comment by aryadas98** [comment]
How can we check whether the accuracy of the results? The residuals only check the accuracy of the filtered data.

**Comment by Alexandros23Kazantzidis** [comment]
Hello Arya Das I tried to run the main.py after your changes in Lamberts_Kalman and it produces an error. Take a look at it and tell me if the same error occurs when you run it on your system.
issue_99 bug

**Comment by aryadas98** [comment]
Yes, the same error occurs in my machine too. Actually, the default orbit.csv file has data in metres while the files in `src` folder have data in kilometres. So while running main.py with the default orbit.csv you have to change the units to metres. Otherwise some overflow will occur. So the correct command would be `python3 main.py -u m`.

**Comment by Alexandros23Kazantzidis** [comment]
Hey, we have not merged these two changes yet. Lambert's revolution set to 0 and the cosine clip. I think they are correct and we should. Have you done any changes to them?

**Comment by Alexandros23Kazantzidis** [comment]
Wait I want to make another comment. Have you checked the Lambert's revolution to be 1? What exactly 0 means?

**Comment by aryadas98** [comment]
No, I haven't changed anything. 0 means that it's calculating the state for the current orbit. 1 means it will calculate the state for both the current and the next orbit. That parameter can be safely set to one because we are taking the first element of the array only, anyway. I have checked with 0 and 1. And by default, that parameter is 5. All give same results.

**Comment by aryadas98** [comment]
@Alexandros23Kazantzidis shall I merge this?

**Comment by Alexandros23Kazantzidis** [comment]
Ok done

**Pull request merged**
