### PR TITLE
WIP: Parsing for UK & IOD file formats

### PR DESCRIPTION
**Pull request by krishna-birla**
Files changed: created satobs.py
Purpose: functions to parse and print UK & IOD format data added
Future work: inter frame coordinate conversion
Notes: Since the branch was created from latest copy of master, those commits are also present

### CODE REVIEW

**Comment by krishna-birla** [comment]
> I haven't checked the maths but it seems fine to me.
> Writing "Helper function" will not work in documentation, properly mention the use/need of the function.

Okay! I'll organize stuff here in the next commit.

**Comment by krishna-birla** [comment]
Files changed: Satobs.py, Sites.gjson (created), requirements.txt
Purpose: Implemented reading data from file system instead of hardcoding, changes as per review, created a GeoJSON file for site data and implemented it in parser, removed version for astropy as suggested by A.H.

**Comment by aryadas98** [comment]
Shall I merge this?

**Comment by aakash525** [comment]
Sure.

**Pull request merged**
