### PR TITLE
Cleaning up the code and removing errors and exceptions

### PR DESCRIPTION
**Pull request by krishna-birla**
File(s) changed: $PROJ$/orbitdeterminator/test_deploy/deployable.py
Purpose: Increases code consistency

### CODE REVIEW

**Comment by krishna-birla** [comment]
File(s) changed: $PROJ$/orbitdeterminator/kep_determination/gibbsMethod.py
Purpose: Removing file errors, generating output in required format, file handling, exception handling
Notes: Output format is different from other determinators to pass pytest, actual output is commented

**Comment by krishna-birla** [comment]
File(s) changed: $PROJ$/orbitdeterminator/kep_determination/gibbsMethod.py
Purpose: Squashing previous commits: Removing file errors, generating output in required format, file handling, exception handling
Notes: Output format is different from other determinators to pass pytest, actual output is commented

**Comment by krishna-birla** [comment]
**Files changed:** $PROJ${orbitdeterminator/automated.py; orbitdeterminator/main.py; orbitdeterminator/kep_determination/gibbsMethod.py; orbitdeterminator/kep_determination/interpolation.py; orbitdeterminator/propagation/sgp4.py; orbitdeterminator/tests/test_gibbsMethod.py}
**Purpose:** Handles **math exceptions and value exceptions**, makes the **output more readable**, few fixes for gibbsMethod, Gives **output for all methods**, graph plotting is optional now, automated.py has a **git deinit functionality**, test files changed to match the output format consistently, 7th element **(revolutions per second) added** to keplerian elements
**Awaiting critical response.**

**Comment by krishna-birla** [comment]
Files changed: main.py, automated.py, lamberts_kalman.py, gibbsMethod.py, deployable.py, folders and result files
Purpose: The interface now works for all four methods and shows rev/day as well. Structured database implemented. Space complexity and time complexity improved. Output is now user friendly. Default mode changed to TripleMoving->SavGol->CubicSpline. Files with multiple headers and different delimiters supported in gibbsMethod. Bug removal from previous commits. Spelling check. Inline comments.
Notes: Merge conflict resolved without changing the workflow.

**Comment by vidhanarya** [comment]
This is not a review just some suggestions. Although overall codebase will be improved, its commit history will get affected as in this PR commits are kind of messy (just my opinion). The last commit could have been avoided by use of rebasing on the current branch. There are two types of changes in this PR cleanup and enhancements, try to keep different kind of changes in different branches and sending two PRs, that way mentors will be able to easily check through your changes. Your changes in the interface I developed in PR #152 are good and it doesn't defeat the purpose, that interface is just a prototype and actual clean interface will be developed during GSoC so its gonna be changed anyway.

**Comment by aryadas98** [comment]
Checked the files changed. Looks mostly okay, except that main.py is already clean and a lot of it has been changed for no reason.

**Comment by krishna-birla** [comment]
> Checked the files changed. Looks mostly okay, except that main.py is already clean and a lot of it has been changed for no reason.

I have tried to make changes only if they improve grammar, presentation, logic or make the output compact and clean. But anyway if changes seem redundant, I am sorry for that. Will keep in mind from next time. :)

**Pull request merged**
