### PR TITLE
Added Google style docstrings

### PR DESCRIPTION
**Pull request by aryadas98**
Added Google style docstrings and also added Molniya 2-10 satellite to unit tests because it is in a highly eccentric orbit. So it will be a good test for HEOs.

### CODE REVIEW

**Comment by aryadas98** [comment]
@Alexandros23Kazantzidis could you please check whether the docstrings are following the sphinx format or not? I tried my best. :)

**Comment by aryadas98** [comment]
Yes, I too wanted to put variable types but couldn't understand how.

**Comment by aryadas98** [comment]
@Alexandros23Kazantzidis I added the data types of the arguments and the return values.

**Comment by Alexandros23Kazantzidis** [comment]
Ok nice you can proceed with the merge.

**Pull request merged**
