### PR TITLE
Added Wiener's filter in filters and made changes in main.py and Added a functionality to animate Orbits around sphere of radius 6400km i.e Earth

### PR DESCRIPTION
**Pull request by archithadge**
Wiener's filter is another filter used to filter data like Savitzky-Golay and triple moving average. I've added an option for this in main and made its module.

### CODE REVIEW

**Comment by vidhanarya** [comment]
Can you please also add a working GIF of the filter in the description and how it compares to previous filters?

**Comment by hornig** [comment]
@nileshchat @Alexandros23Kazantzidis  what do you think?

**Comment by Alexandros23Kazantzidis** [comment]
Seems pretty good I suggest we proceed with merging. I will try to look into the results of Wiener's filter in some of the tests files
@hornig  @nileshchat

**Comment by hornig** [comment]
> Seems pretty good I suggest we proceed with merging. I will try to look into the results of Wiener's filter in some of the tests files
> @hornig @nileshchat

Can you briefly explain, how you wanna test it? Will you add these files to the project?

**Comment by hornig** [comment]
I checked functions with the filter and it works without errors.
what I do not know is why the results are so different to the other filters.
for example with c:\Python37\python.exe main.py -u m and Cube Spline Interpolation, the semi major axis is really way off. the other options are closer to what the other filters generate.
how is it like this @archithadge ?

**Comment by hornig** [comment]
merged it.
thx @archithadge and @Alexandros23Kazantzidis . Maybe we need to fix some stuff when it breaks. but so far, let's have it included.

**Pull request merged**
