### PR TITLE
Ellipse fit method

### PR DESCRIPTION
**Pull request by aryadas98**
I added a new file called `ellipse_fit.py`. It can be run using `python3 ellipse_fit.py -f <file_name> -u <units>`

Sample output:
```
Semi-major axis:             6752.376692997214 km
Eccentricity:                0.6159007693160585
Argument of periapsis:       1.721040085772447 rad
Inclination:                 0.10403555768244305 rad
Longitude of Ascending Node: 1.8624357725304346 rad
```

orbit

### CODE REVIEW

**Comment by aryadas98** [comment]
The Earth is currently not plotted to scale because if I do so, some orbits go below the surface of the Earth. I think the data in the csv files are not in metres or kilometres. Additionally, I think we should switch to some other 3D plotting library. Matplotlib is good for 2D plotting, but there isn't proper support for 3D plotting. For example, there is no option to set the aspect ratio of the axes in 3D.

**Comment by Alexandros23Kazantzidis** [comment]
Hello Arya, I read the code but can you give me a small description of what the script does. How do you find the ellipse from the points? Because points have noise we don't want the noisy points to participate in the computation of the parameters of the ellipse.

**Comment by aryadas98** [comment]
For all kinds of minimization, I have currently used the Nelder-Mead method. It can be improved if we use some other method.

The algorithm works like this:
1. First, find out the best-fit plane. The best-fit plane is that plane which is closest to all the points. The best-fit plane should also pass through the origin as every orbit has one focus at origin. Currently, I have used Nelder-Mead for this also, but since this is a linear problem, more direct methods can be used.
2. Now, project all the points onto this plane. From the orientation of the plane, the inclination and longitude of ascending node can be determined. (± 90 degrees, because this method doesn't make use of time information at all. So, the direction of the orbit can't be determined.)
3. The aim is to convert the problem into a 2D problem. We need a basis that spans the plane. One natural choice is to choose the vector along the longitude of ascending node. This also allows us to determine argument of periapsis without any extra coordinate transformmations. And the other vector would be one lying 90 degrees from it. These two vectors must be normalized. Together, they form an orthogonal "unit" basis of the plane. Such a basis is required so that the shape and size of the orbit remains unchanged.
4. Now, find the coordinates of all the points in terms of these basis vectors. The problem is now a 2D problem. Convert the coordinates from cartesian to polar.
5. The equation of an ellipse in polar coordinates with one focus at origin is:
image
So let's define an error function as follows:
image
Now the task is to find the parametres a,e and omega that minimize the error function. This is handled by the Nelder-Mead solver in the SciPy package. The solver requires an initial guess. Let r and R be the minimum and maximum radii respectively. Then a0 = (r+R)/2, e0 = (R-r)/(R+r), omega0 = index of r.
6. After minimization, all the Keplerian elements have been found. Now generate some more points and plot the results.

**Comment by aryadas98** [comment]
I have added inline documentation to the code for easier understanding.

**Comment by Alexandros23Kazantzidis** [comment]
Nice, good work man. I want to test it with one of my scripts which I think it kinda does the same. One more question if I may, which csv data you used to do the above graph? In the file it may have the keplerian elements of the "correct" orbit and you can check it with yours. To see how close you are with your approach.

**Comment by aryadas98** [comment]
I don't remember the exact file I used for making this graph. However, I tested this with all the files in the repo. I also created some "partial" files (files with data for only half or a quarter of the orbit). The files in the example_data folder have the correct parameters written in their file names. So I compared and saw that it's pretty close.

**Comment by Nilesh4145** [comment]
@aryadas98 could you please put your code in a proper directory.

**Comment by aryadas98** [comment]
Sorry, I have put the file in the kep_determination directory now.

**Pull request merged**
