### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by nileshchat**
Update requirements file to install the latest version of listed libraries.

### CODE REVIEW

**Comment by hornig** [comment]
progress so far with installing requirements.txt
Python3.7 64bit, windows10, ok, all files installed
Python3.8 64bit, windows10, not-ok, all files installed but pykep. pykep has no windows version for python3.8 yet.

**Comment by hornig** [comment]
the installed libs from this requirements work with the main.py.
all optioned used and make results without errors.
only tested with python 3.7 64 bit windows 10.

would be good to hear a comment by linux users and/or anaconda users.

**Comment by hornig** [comment]
if there will be problems with people, we will re-open an issue.
I will merge it, because it is a minor change

**Comment by mfa** [comment]
not pinning versions is a really bad idea!
you want control over versions to guarantee same deployment everywhere (without breaking stuff only by installing it 1 day later).

**Pull request merged**
