### PR TITLE
Tweaks to the readme

### PR DESCRIPTION
**Pull request by lonesword**
Towards #104

### CODE REVIEW

**Comment by lonesword** [comment]
@Nilesh4145 Please see if this is accurate and merge if useful.

**Comment by Nilesh4145** [comment]
@lonesword please have a look at the documentation [here](http://orbit-determinator.readthedocs.io/en/latest/?badge=latest). I believe there is one more method of installation. For now, this is good. It will be great if you could improve it further.

**Comment by Alexandros23Kazantzidis** [comment]
This pull request can be merged I think. We have installation guide into the documentation but it could be useful to have it at the readme file also

**Comment by lonesword** [comment]
@Nilesh4145 @Alexandros23Kazantzidis I did not know that there was a documentation! The link was a little hard to find. I've changed the pull request to add a normal link to the documentation. Thanks for pointing this out.

**Pull request merged**
